# Generated by Django 4.2.23 on 2025-08-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gmailShareConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_user', models.EmailField(default='littlecapa@googlemail.com', max_length=254)),
                ('source_folder', models.CharField(default='Aktien', max_length=255)),
                ('target_folder', models.CharField(default='Archive_Aktien', max_length=255)),
                ('save_path', models.CharField(default='/Volumes/Data/DataLake/Finance/Test', max_length=500)),
            ],
        ),
    ]
