# Generated by Django 4.2.23 on 2025-09-21 10:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stock_recommendation_alarm_holdings'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='notes',
            field=models.TextField(blank=True, help_text='Persönliche Notizen zu diesem Alarm', null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='threshold_value_high',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Schwellwert (Preis)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='threshold_value_low',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Schwellwert (Preis)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='isin',
            field=models.CharField(help_text='Internationale Wertpapierkennnummer (12 Zeichen)', max_length=12, primary_key=True, serialize=False, verbose_name='ISIN'),
        ),
    ]
