# Generated by Django 4.2.23 on 2025-10-02 07:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alarm_notes_alter_alarm_threshold_value_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdings',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Basis Investment'), (2, 'Dividende'), (3, 'D/EU'), (4, 'US Tech'), (5, 'World Tech'), (6, 'Compounder'), (99, 'Sonstiges')], default=99, help_text='Vertrauensgrad der Empfehlung', null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='action',
            field=models.CharField(choices=[('buy', 'Kaufen'), ('sell', 'Verkaufen'), ('hold', 'Halten'), ('strong_buy', 'Stark Kaufen'), ('strong_sell', 'Stark Verkaufen'), ('watch', 'Beobachten'), ('volatile', 'Volatil')], default='hold', help_text='Empfohlene Aktion', max_length=15),
        ),
        migrations.CreateModel(
            name='DecicionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buy', 'Kaufen'), ('sell', 'Verkaufen'), ('hold', 'Halten')], default='hold', help_text='Empfohlene Aktion', max_length=5)),
                ('source', models.CharField(help_text='Quelle der Empfehlung (Analyst, Bank, Website, etc.)', max_length=100)),
                ('next_step_price', models.DecimalField(blank=True, decimal_places=4, help_text='Kursziel', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('publication_date', models.DateField(blank=True, help_text='Datum der Veröffentlichung', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decicions', to='core.stock')),
            ],
            options={
                'verbose_name': 'Entscheidungsprotokoll',
                'verbose_name_plural': 'Entscheidung',
                'ordering': ['-publication_date'],
            },
        ),
    ]
