# Generated by Django 4.2.23 on 2025-10-02 07:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_holdings_category_alter_recommendation_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decicionlog',
            name='execution_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Kursziel', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
