# Generated by Django 4.2.23 on 2025-10-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_decicionlog_execution_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decicionlog',
            options={'ordering': ['-publication_date'], 'verbose_name': 'Entscheidungsprotokoll', 'verbose_name_plural': 'Entscheidungen'},
        ),
        migrations.AddField(
            model_name='decicionlog',
            name='reasoning',
            field=models.TextField(blank=True, default='', help_text='Begründung für die Entscheidung', null=True),
        ),
        migrations.AlterField(
            model_name='decicionlog',
            name='source',
            field=models.CharField(blank=True, help_text='Quelle der Empfehlung (Analyst, Bank, Website, etc.)', max_length=100, null=True),
        ),
    ]
