# Generated by Django 4.2.23 on 2025-10-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_decicionlog_options_decicionlog_reasoning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_etf',
            field=models.BooleanField(default=True, help_text='Ist es ein ETF?'),
        ),
    ]
