# Generated by Django 4.2.23 on 2025-10-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_stock_is_etf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='is_etf',
            field=models.BooleanField(default=False, help_text='Ist es ein ETF?'),
        ),
    ]
