# Generated by Django 4.2.23 on 2025-10-08 17:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_stock_is_etf'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Höhe des Sparplans', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('frequency', models.IntegerField(blank=True, choices=[(1, 'Weekly'), (2, 'Monthly'), (3, 'Quarterly')], default=2, help_text='Ausführungsintervall des Sparplans  ', null=True)),
                ('start_date', models.DateField(help_text='Startdatum des Sparplans')),
                ('is_valid', models.BooleanField(default=True, help_text='Sparplan ist aktiv')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_plans', to='core.stock')),
            ],
        ),
    ]
