# Generated by Django 4.2.23 on 2025-10-09 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_savingplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingplan',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='savingplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='savingplan',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='savingplan',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
    ]
