# Generated by Django 4.2.23 on 2025-10-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_savingplan_is_valid_savingplan_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
