# Generated by Django 4.2.23 on 2025-10-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_savingplan_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
